---
# Playbook to add users defined in the "users" list to a system. 
# Define "local" as the hosts and connection if running on local box.
- hosts: "localhost"
  connection: "local"
  vars:
    users:
    - bobbuilder

# Creates user accounts using the names defined under vars: -> users:. Adds the users to the groups defined. Wheel is used in RHEL for sudo privlege
  tasks:
  - name: Create user account and add user to group
    user:
      name: "{{ item }}"
      groups: "wheel"
    with_items: "{{ users }}"

# Adds the users key to their authorized_keys file, pulling from the files folder. Must match the users "name" + .pubS
  - name: "Add authorized keys"
    authorized_key:
      user: "{{ item }}"
      key: "{{ lookup('file', 'files/'+ item + '.pub') }}"
    with_items: "{{ users }}"